apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-clone-frontend
spec:
  selector:
    matchLabels:
      run: yelp-clone-frontend
  replicas: 1
  template:
    metadata:
      labels:
        run: yelp-clone-frontend
    spec:
      containers:
      - name: yelp-clone-frontend
        image: julianvega/yelp-clone-frontend:0.0.6
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: yelp-clone-frontend
  labels:
    run: yelp-clone-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    run: yelp-clone-frontend