apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yelp-clone-backend
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/JAVegaG/yelp-clone-k8s
    targetRevision: develop
    path: client
  destination:
    server: https://kubernetes.default.svc
    namespace: yelp-clone

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true